# Generated by Django 5.2.3 on 2025-06-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simpleuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="simpleuser",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
