# Generated by Django 5.2.3 on 2025-06-27 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simpleuser",
            name="last_password_change",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
