# Generated by Django 5.2.3 on 2025-06-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_simpleuser_id_alter_simpleuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simpleuser",
            name="id",
        ),
        migrations.AlterField(
            model_name="simpleuser",
            name="username",
            field=models.CharField(
                max_length=150, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
